/** @format */

export const {
  ITERABLE_API_BASE_URL,
  ITERABLE_API_KEY,
  ITERABLE_WAITLIST_ID,
  ZENDESK_BASE_URL,
  ZENDESK_API_KEY,
  ZENDESK_TEND_AT_WORK_RECIPIENT,
  NEXT_SERVER_IP2LOCATION_API_KEY,
  IP2LOCATION_BASE_URL,
} = process.env;
